GET http://localhost:3000/transactions

###
POST http://localhost:3000/transactions
Content-Type: application/json
Accept: application/json

{
  "Customer": {
    "email": "customer.email@email.com"
  },
  "Billing": {
    "BillingAddress": {
      "Firstname": "Jean",
      "Lastname": "Bon",
      "Address": "68 Place Charles de Gaulle",
      "City": "VILLENEUVE-D",
      "Zipcode": "59791",
      "Country": "France"
    }
  },
  "Shipping": "Fast delivery",
  "ShoppingCart": ["article 1", "article 2", "article 3"],
  "Price": "15€"
}

###
GET http://localhost:3000/transactions/5ed50d427915a1022f901435