GET http://localhost:3000/transactions

###
POST http://localhost:3000/transactions
Content-Type: application/json
Accept: application/json

{
  "Customer": {
    "email": "customer.email@email.com"
  },
  "Billing": {
    "BillingAddress": {
      "Firstname": "Jean",
      "Lastname": "Bon",
      "Address": "68 Place Charles de Gaulle",
      "City": "VILLENEUVE-D",
      "Zipcode": "59791",
      "Country": "France"
    }
  },
  "Shipping": "Fast delivery",
  "ShoppingCart": [
    { "name": "article 1", "price": "15€", "refunded": false },
    { "name": "article 2", "price": "20€", "refunded": true },
    { "name": "article 3", "price": "30€", "refunded": false }
  ],
  "TotalPrice": "65€"
}

###
PUT http://localhost:3000/transactions/5eff40de0534290174ed2cfe
Content-Type: application/json
Accept: application/json

{
  "Customer": {
    "email": "customer.email@email.com"
  },
  "Billing": {
    "BillingAddress": {
      "Firstname": "Jean",
      "Lastname": "Bon",
      "Address": "68 Place Charles de Gaulle",
      "City": "VILLENEUVE-D",
      "Zipcode": "59791",
      "Country": "France"
    }
  },
  "Shipping": "Fast delivery",
  "ShoppingCart": [
    { "name": "article 1", "price": "15€", "refunded": "false" },
    { "name": "article 2", "price": "20€", "refunded": "true" },
    { "name": "article 3", "price": "30€", "refunded": "false" }
  ],
  "TotalPrice": "65€"
}

###
GET http://localhost:3000/transactions/5ed50d427915a1022f90143

###
DELETE http://localhost:3000/transactions/5ef3645795a2fa00ec1d56ea

###