scrapping:
		docker-compose exec server node scrapping.js
install:
		docker-compose exec server npm i
i-pkg:
		docker-compose exec server npm i $(pkg)
db:
		docker-compose exec db psql -U root -W api 
